### ISSUE TITLE
Parsing USA numbers without explicit '+1" doesn't work

### ISSUE THREAD

**Issue by mlsquires** [carr/phone#4]
"+1 206 973 5100" parses out just fine.

"206 973 5100", :country_code => '1' - doesn't work
"206 973 5100" with a default_country_code set to '1' doesn't work

However, the following (which are NOT standard USA forms) _do_ parse:
"0206 973 5100", :country_code => '1' - works
"0206 973 5100" with a default_country_code set to '1' works

The basic issue seems to be that 'split_to_parts' has this line:
      string = string.gsub(country.country_code_regexp, '0')

and 'formats' has this line:
:short => Regexp.new('^0(' + area_code_regexp + ')' + NUMBER)

There appears to be a presumption that a full number _without_ a country code begins with a zero. That certainly isn't true for USA numbers. Changing those two lines to remove the zero works for USA numbers, but breaks other tests.

If we change the line in 'formats' to be this:
      :short => Regexp.new('^[0]?(' + area_code_regexp + ')' + NUMBER),

(that is, make the leading zero optional rather than mandatory), then it parses USA numbers fine and continues to pass all of the tests in the test suite.

Does this fix make sense?

Thanks,
Michael Lee Squires
msquires@whitepages.com

**Comment by cgarvis** [comment]
Just ran into this.  Would love to have a fix.
